- id: '1681088653338'
  alias: My First Automation
  description: Toggles front studio lights if still images is turned on/off on media
    room camera.
  trigger:
  - platform: device
    type: changed_states
    device_id: 41972a7041c0c89c1c3dc56600bffd32
    entity_id: switch.http_motionpi4_mediaroom_config_2_still_images
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 0
    enabled: true
  condition: []
  action:
  - type: toggle
    device_id: 0b29ee9b13cb102d5180d84f7c5d6cf2
    entity_id: light.studio_front_left
    domain: light
  - type: toggle
    device_id: 089eea60e5cd55992b9630b5826e97d6
    entity_id: light.studio_front_right
    domain: light
  mode: single
- id: '1681103237763'
  alias: Jennifer Weekday Wakeup
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: 02:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.master_bedroom_jenn_wakeup_scene
    metadata: {}
  mode: single
- id: '1681112266135'
  alias: Scheduled Backup
  description: Full backup daily @ 5AM
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data:
      compressed: true
  mode: single
- id: '1681162686311'
  alias: Config Backup (github)
  description: 'Backs up config only to GitHub. See: https://www.youtube.com/watch?v=hhv-WqGUy_o'
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1681172168513'
  alias: 'GeoFence: Kary Arrival'
  description: Automates anything that needs to happen if I go somewhere.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home_kary
    attribute: nearest
    below: 1.2
    id: approaching-home
  condition:
  - condition: state
    entity_id: proximity.home_kary
    attribute: dir_of_travel
    state: towards
  action:
  - service: shell_command.trigger_garage_door
    data: {}
  - device_id: d35c55fdf0c65dc924d73235bcf2b1e6
    domain: climate
    entity_id: climate.third_floor_thermostat_nativezone
    type: set_preset_mode
    preset_mode: Home
  mode: single
- id: '1681176128676'
  alias: 'GeoFence: Kary Departure'
  description: Automates various items when I'm > 5 miles away.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home_kary
    above: 2
  condition: []
  action:
  - device_id: d35c55fdf0c65dc924d73235bcf2b1e6
    domain: climate
    entity_id: climate.third_floor_thermostat_nativezone
    type: set_preset_mode
    preset_mode: Away
  - type: turn_off
    device_id: a729c76cf13a963a496450a6849a34da
    entity_id: switch.mss110_f450_outlet1
    domain: switch
  mode: single
- id: '1681176379895'
  alias: Kary Wakeup
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.master_bedroom_daylight_scene
    metadata: {}
  - service: notify.smtpmail
    data:
      message: Test Email Notification
      title: Test Email Notification
      target: 7047705271@vtext.com
  mode: single
- id: '1681176443864'
  alias: Jennifer Bedtime
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 55909bcf92092e92af906cb9569db605
    entity_id: light.mb_room_kary
    domain: light
  - type: turn_off
    device_id: d98bf52e5929d96e7ebfe43422f79ceb
    entity_id: light.mb_room_jenn
    domain: light
  mode: single
- id: '1681230306765'
  alias: 'Perimeter Alarm '
  description: Fires when any perimeter alarm triggers.
  trigger: []
  condition: []
  action: []
  mode: single
- id: '1681251459538'
  alias: Rubber Tree Plant Light Automation
  description: Turns rubber tree plant light on and off on a schedule.
  trigger:
  - platform: state
    entity_id:
    - schedule.rubber_tree_light_schedule
    attribute: next_event
  condition: []
  action:
  - type: toggle
    device_id: 25f4eea66b13269d8c226d4571e2cf40
    entity_id: switch.mss110_f6a8_outlet1
    domain: switch
  mode: single
- id: '1681318225531'
  alias: Email Notify Test
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.smtpmail
    data:
      message: test6
      target: 7047705271@vtext.com
      title: asdf
      data: sdfg
  mode: single
