- id: '1681103237763'
  alias: Jennifer Weekday Wakeup
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: 02:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.master_bedroom_jenn_wakeup_scene
    metadata: {}
  mode: single
- id: '1681112266135'
  alias: Scheduled Backup
  description: Full backup daily @ 5AM
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: hassio.backup_full
    data:
      compressed: true
  mode: single
- id: '1681162686311'
  alias: Config Backup (github)
  description: 'Backs up config only to GitHub. See: https://www.youtube.com/watch?v=hhv-WqGUy_o'
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1681172168513'
  alias: 'GeoFence: Kary Arrival'
  description: Automates anything that needs to happen if I go somewhere.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home_kary
    attribute: nearest
    below: 1
    id: approaching-home
  condition:
  - condition: state
    entity_id: proximity.home_kary
    attribute: dir_of_travel
    state: towards
  action:
  - service: shell_command.trigger_garage_door
    data: {}
  - device_id: d35c55fdf0c65dc924d73235bcf2b1e6
    domain: climate
    entity_id: climate.third_floor_thermostat_nativezone
    type: set_preset_mode
    preset_mode: Home
  - service: climate.set_temperature
    data:
      temperature: 72
      hvac_mode: auto
      target_temp_high: 72
      target_temp_low: 70
    target:
      device_id: d35c55fdf0c65dc924d73235bcf2b1e6
  mode: single
- id: '1681176128676'
  alias: 'GeoFence: Kary Departure'
  description: Automates various items when I'm > 5 miles away.
  trigger: []
  condition:
  - condition: device
    device_id: 73a225063e981ddb1e941cf746eb6d5f
    domain: device_tracker
    entity_id: device_tracker.sm_s918u_karyphone
    type: is_not_home
  action:
  - type: turn_off
    device_id: a729c76cf13a963a496450a6849a34da
    entity_id: switch.mss110_f450_outlet1
    domain: switch
  - service: climate.set_temperature
    data:
      hvac_mode: auto
      temperature: 72
    target:
      entity_id: climate.third_floor_thermostat_nativezone
  mode: single
- id: '1681176379895'
  alias: Kary Wakeup
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.master_bedroom_daylight_scene
    metadata: {}
  - service: notify.smtpmail
    data:
      message: Test Email Notification
      title: Test Email Notification
      target: 7047705271@vtext.com
  mode: single
- id: '1681176443864'
  alias: Jennifer Bedtime
  description: Bedroom lights come on dimly @ 2:30 AM
  trigger:
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 55909bcf92092e92af906cb9569db605
    entity_id: light.mb_room_kary
    domain: light
  - type: turn_off
    device_id: d98bf52e5929d96e7ebfe43422f79ceb
    entity_id: light.mb_room_jenn
    domain: light
  mode: single
- id: '1681230306765'
  alias: 'Perimeter Alarm '
  description: Fires when any perimeter alarm triggers.
  trigger: []
  condition: []
  action: []
  mode: single
- id: '1681251459538'
  alias: Rubber Tree Plant Light Automation
  description: Turns rubber tree plant light on and off on a schedule.
  trigger:
  - platform: state
    entity_id:
    - schedule.rubber_tree_light_schedule
    attribute: next_event
  condition: []
  action:
  - type: toggle
    device_id: 25f4eea66b13269d8c226d4571e2cf40
    entity_id: switch.mss110_f6a8_outlet1
    domain: switch
  mode: single
- id: '1681318225531'
  alias: Email Notify Test
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.smtpmail
    data:
      message: test6
      target: 7047705271@vtext.com
      title: asdf
      data: sdfg
  mode: single
- id: '1681398116414'
  alias: Big Room Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: ba69097dbafc9cf0318ce29dc65d8819
    entity_id: binary_sensor.esp_bigroom_motion_big_room_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - type: turn_on
    device_id: ba69097dbafc9cf0318ce29dc65d8819
    entity_id: light.esp_bigroom_motion_esp_bigroom_motion_led
    domain: light
    flash: long
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_off
    device_id: ba69097dbafc9cf0318ce29dc65d8819
    entity_id: light.esp_bigroom_motion_esp_bigroom_motion_led
    domain: light
  mode: single
- id: '1681407583262'
  alias: Garage Door opened
  description: The garage door has just been opened.
  trigger:
  - type: opened
    platform: device
    device_id: 6c480a1cc454af02f2aa40e7a4c6b4fa
    entity_id: binary_sensor.garage_door_alarm_window_door_is_open_2
    domain: binary_sensor
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 8
      seconds: 0
      milliseconds: 0
  - if:
    - type: is_open
      condition: device
      device_id: 6c480a1cc454af02f2aa40e7a4c6b4fa
      entity_id: binary_sensor.garage_door_alarm_window_door_is_open_2
      domain: binary_sensor
    then:
    - device_id: 73a225063e981ddb1e941cf746eb6d5f
      domain: mobile_app
      type: notify
      message: Garage Door Baby
      title: Garage Door auto-closed.
    - service: shell_command.trigger_garage_door
      data: {}
    else:
    - stop: Door is already closed.
    - service: shell_command.trigger_garage_door
      data: {}
  - service: shell_command.play_local_notification
    data: {}
    enabled: false
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_id: media-source://media_source/local/garage-door-closed.mp3
      media_content_type: audio/mpeg
    metadata:
      title: garage-door-closed.mp3
      thumbnail:
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://media_source
  mode: single
- id: '1681433347838'
  alias: Telnet Audio
  description: Testing broadcasting audio messages to a remote pi.
  trigger:
  - type: motion
    platform: device
    device_id: ba69097dbafc9cf0318ce29dc65d8819
    entity_id: binary_sensor.esp_bigroom_motion_big_room_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet_2
    data:
      media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
      media_content_type: provider
    metadata:
      title: Warning, potential intruder in front living room. Initiating kill shot
        in 10 seconds!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
      media_content_type: provider
    metadata:
      title: Warning, potential intruder in front living room. Initiating kill shot
        in 10 seconds!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet_3
    data:
      media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
      media_content_type: provider
    metadata:
      title: Warning, potential intruder in front living room. Initiating kill shot
        in 10 seconds!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Warning%2C+potential+intruder+in+front+living+room.+Initiating+kill+shot+in+10+seconds%21
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1681481570844'
  alias: BStation Volume Warning
  description: Notify if the status of Volume 1 is not "normal"
  trigger:
  - platform: state
    entity_id:
    - sensor.bstation_volume_1_status
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - service: notify.smtpmail
    data:
      message: BStation Volume 1 Status has changed to {{ states("sensor.bstation_volume_1_status")
        }}. Please check Home Assistant.
  - service: notify.mobile_app_sm_s918u_karyphone
    data:
      message: 'BStation Volume 1 status has changed to {{ states("sensor.bstation_volume_1_status")
        }}. Please check Home Assistant.  '
      title: BStation Volume 1 Status Change
      data:
        channel: Motion
        sticky: 'true'
        importance: high
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: notify.smtpmail
    data:
      message: BStation volume status has changed from normal. Please check BStation.
      title: BStation Warning
      target: 7047705271@vtext.com
  mode: single
