# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Shell Commands
shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
  trigger_garage_door: curl -A 'HA-Shell' 'http://192.168.2.88/772c3a64-7628-4c61-825c-39293d2ea94f'
  play_local_notification: "ffplay -nodisp -vn /config/audio/garage-door-closed.wav"

#Iframe Panels
#panel_iframe:
#
#  moship:
#    title: "The Mothership"
#    url: "http://iot.buildingtheborg.com/themothership"
#
#  pihole:
#    title: "Pi-Hole"
#    url: "http://192.168.2.69/admin"

# Proximity and Zones config
proximity:
  home_all:
    devices:
      - person.kary
      - proximity.home_kary
      - person.jenn
    tolerance: 50
    unit_of_measurement: mi

  home_kary:
    devices:
      - person.kary
      - proximity.home_kary
    tolerance: 50
    unit_of_measurement: mi

  home_jennifer:
    devices:
      - person.jenn
    tolerance: 50
    unit_of_measurement: mi

# Sensors
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: memory_use_percent
      - type: load_1m
      - type: load_15m
      - type: processor_use
      - type: processor_temperature

# SMTP Email
notify:
  - platform: smtp
    name: smtpmail
    server: smtp.office365.com
    port: 587
    timeout: 15
    sender: !secret notification_sender
    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient:
      - !secret notification_recipient_kary
    sender_name: Home Assistant
    debug: true

# Example configuration.yaml entry
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: "1111"
    arming_time: 60
    delay_time: 40
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

      # Motion Sensors
  #device_tracker:
#  - platform: netgear
#    host: 192.168.2.1
#    port: 80
#    username: admin
#    password: Che$ter120120120
#    accesspoints:
#      - 94:A6:7E:77:D2:DB # Router
#      - 94:A6:7E:76:40:9C # Satellite_Studio
#      - 94:A6:7E:76:3E:E4 # Sattelite_2ndFloor
#    devices:
#      - 5E:F9:CF:66:46:F7 # kary phone
#      - 0A:5D:DA:85:C8:27 # jenn phone
#    new_device_defaults:
#      track_new_devices: true
#    interval_seconds: 8
#    consider_home: 240
